# zsh配置加载顺序：
# https://wangxiz.site/blog/posts/zsh-startup-and-shotdown-files/#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%8A%A0%E8%BD%BD%E9%A1%BA%E5%BA%8F

DIR=`dirname $0`
source $DIR/env.zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$ZDOTDIR/ohmyzsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
    git
    z
    zsh-syntax-highlighting
    zsh-autosuggestions
    )
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'
source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit p10k.zsh.
source $DIR/p10k.zsh
source $DIR/my-p10k.zsh

source $DIR/aliases.zsh